learning_log/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views
from django.views.static import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
    #path('send_email/', views.send_email, name="send_email")
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path

from . import views
#from .views import send_email

app_name = 'learning_logs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all topics.
    path('topics/', views.topics, name='topics'),
    # Detail page for a single topic.
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding a new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Page for editing an entry.
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    #path('send_email/',send_email, name='send_email'),
    path('users/register/send_email/', views.get_name, name="send_email"),
    path('users/register/ok/', views.ok, name="ok"),
    #path('image/code/', views.img_code,name='code'),
    path('users/remove/',views.remove,name='remove'),
    path('goodbye-mszhao/',views.goodbyemszhao,name='goodbye-mszhao'),
    path('home/',views.important,name='home'),
    path('we-are-married/',views.we_are_married,name='we-are-married'),
    path('brief-introduction',views.brief_introduction,name='brief-introduction'),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
    #path('send_email/', views.send_email, name="send_email"),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    """A topic the user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text

class Entry(models.Model):
    """Something specific learned about a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'entries'
 
    def __str__(self):
        """Return a string representation of the model."""
        return f"{self.text[:50]}..."

learning_logs/forms.py
from django import forms

from .models import Topic, Entry
from django.contrib.auth.models import User
class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}
class NameForm(forms.Form):
        username = forms.CharField(label="用户名称",required=True,widget=forms.widgets.TextInput(attrs={'class': 'form-control', 'placeholder': '请输入注册用户名称'}))
        age = forms.EmailField(label="邮箱",widget=forms.widgets.TextInput(attrs={'class': 'form-control', 'placeholder': '请输入邮箱号'}))
        status = forms.CharField(required=True,label="密码(大于8位数且必须包含大小写)",widget=forms.widgets.TextInput(attrs={'class': 'form-control', 'placeholder': '请输入注册用户密码'}),min_length=8)

class USERSREMOVE(forms.Form):
    user=User.objects.all()
    num=len(User.objects.all())
    b=[]
    for i in range(num):
        a=user[i].username
        b.append(a)
    choice = forms.ChoiceField(label='选择模式',choices=(
        ("2","开始删除用户"),
    ))
    
    usernames = forms.CharField(required=True,label=f"目前用户：{b}",widget=forms.widgets.TextInput(attrs={'class': 'form-control', 'placeholder': '请输入要删除的用户'}))

learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.http import HttpResponse
from django.contrib import messages
from django import forms as djforms
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.core.mail import send_mail
from django.shortcuts import HttpResponse
from learning_log import settings
from .forms import NameForm
from django.http import HttpResponseRedirect
from .forms import NameForm,USERSREMOVE
from django.contrib.auth.models import User
def index(request):
    """The home page for Learning Log."""
    return render(request, 'learning_logs/index.html')

#@login_required
def topics(request):
    """Show all topics."""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    # Make sure the topic belongs to the current user.
    #if topic.owner != request.user:
        #raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)
    
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    # Display a blank or invalid form.
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    #if topic.owner != request.user:
        #raise Http404
    
    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)



def get_name(request):
    if request.method == 'POST':
        # 如果这个表单是post请求，我们需要处理数据
        form = NameForm(request.POST)
        if form.is_valid():  # 检查界面是否传入表单数据
            # 表单数据被存储在 form.cleaned_data 中
            return HttpResponseRedirect('/thanks/')  # 返回一个界面，输入该界面的URL
    else:
        # 如果是一个get请求，将创建一个空表单
        form = NameForm()
    return render(request, 'learning_logs/name.html', {'form': form})

def ok(request):
    a,b,c=NameForm(request.POST)
    try:
        send_mail(
            subject='注册激活',
            message=f'我要注册激活\n用户名：{a}\n邮箱：{b}\n密码：{c}',
            from_email=settings.EMAIL_FROM,  # 发件人
            recipient_list=['3437559454@qq.com'],  # 收件人
            #收件人可以直接写，也可以从setting.py中配置中导入
            fail_silently=False
        )
    except:
        return HttpResponse('网络问题，无法提交！请手动提交申请到:3437559454@qq.com[标题写注册激活，备注好用户名，邮箱号，密码(大于8位数且必须包含大小写)]，审核结果会发送到你的邮箱上！')
    else:
        return HttpResponse('提交成功！\n请等待审核……\n审核结果会发送到你的邮箱上！')
@login_required
def remove(request):
    if request.method == 'POST':
        # 如果这个表单是post请求，我们需要处理数据
        forms = USERSREMOVE(request.POST)
        if forms.is_valid():  # 检查界面是否传入表单数据
            # 表单数据被存储在 form.cleaned_data 中
            for key in request.POST:
                a=request.POST.get(key)
            try:
                User.objects.get(username=str(a)).delete()
            except:
                return HttpResponse(f'没有此用户！')
            else:
                return HttpResponse(f'{a}已被删除!')  # 返回一个界面，输入该界面的URL
    else:
        if request.user.username != "wangziheng":
            return HttpResponse(f'权限不足！！！仅限管理员HJ可更改！！！')
        # 如果是一个get请求，将创建一个空表单
        else:
            forms = USERSREMOVE()
            return render(request, 'learning_logs/remove-list.html', {'forms': forms})
def test(request):
        user=User.objects.all()
        num=len(User.objects.all())
        b=[]
        for i in range(num):
            a=user[i].username
            b.append(a)
        messages.success(request,f'目前用户:{b}')
def goodbyemszhao(request):
    return render(request,'learning_logs/goodbyemszhao.html')
def important(request):
    return render(request,'learning_logs/important.html')
def we_are_married(request):
    return render(request,'learning_logs/we-are-married.html')
def brief_introduction(request):
    return render(request,'learning_logs/brief_introduction.html')

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
  <link rel="stylesheet" type="text/css" href="/static/try.css">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
  <title>Baboon协会</title>
  <link href="https://imglf4.lf127.net/img/849b290ea4e99b85/RE90NFpEV1NHVzNwQnRlNVhMUXpSS2NINlJ3VzZUVnVZd3dHaE5Ja2haST0.png?imageView&thumbnail=1000x0&type=png" rel="icon" type="image/x-ico">

  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}

</head>

  
<script>
  var noPrint=true;
  var noCopy=false;
  var noScreenshot=true;
  var autoBlur=false;
</script>
<script type="text/javascript" src="https://pdfanticopy.com/noprint.js"></script>
<body>
  
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <img src="https://imglf4.lf127.net/img/849b290ea4e99b85/RE90NFpEV1NHVzNwQnRlNVhMUXpSS2NINlJ3VzZUVnVZd3dHaE5Ja2haST0.png?imageView&thumbnail=1000x0&type=png" height="45" width="45">

    <a class="navbar-brand" href="{% url 'learning_logs:index'%}">
        Baboon协会</a>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'learning_logs:home'%}">
              功能</a></li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text"}">欢迎你, {{ user.username }}.</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">退出登录</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">注册</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">登录</a></li>
        {% endif %}
    </div>

  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
    
  </main>

</body>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312" />

<style type="text/css">
body {
padding: 0;
margin: 0 auto;
}
#footer {
height: 100px;
line-height: 100px;
bottom: 0;
width: 100%;
text-align: center;
background: grey;
color: #fff;
font-family: Arial;
font-size: 12px;
letter-spacing: 1px;
}
.content {
height: 1800px;
width: 100%;
text-align: center;
}
</style>
</head>
<style>
  no{
    font-size: 120px;
  }
</style>
&nbsp;
<no style="text-indent:2em;"> </no>

<body>
<div id="footer">©2021-2023 baboonassociation &nbsp;&nbsp; 联系我们：3437559454@qq.com </div>
</body>
</html>

learning_logs/templates/learning_logs/brief_introduction.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}
{% block content %}
{% bootstrap_css %}
<h3><strong><p>网站简介：</p></strong></h3>
<img src="https://imglf3.lf127.net/img/11f16e6475ad838a/RE90NFpEV1NHVzNwQnRlNVhMUXpSS1c2K1NYZWJ4L0szc2Y5N2FEVXgrND0.png?imageView&thumbnail=1680x0&quality=96&stripmeta=0">
<p></p>
<img src="https://imglf4.lf127.net/img/c4045c1e2427119e/RE90NFpEV1NHVzNwQnRlNVhMUXpST2kwL2dQSFdRUXVwVVZTK3RXWGZRRT0.png?imageView&thumbnail=1680x0&quality=96&stripmeta=0">
<p></p>
<a href="/" style="color: gray;">点我返回</a>
{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
    
  <p>Edit entry:</p>
    
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary input-sm" name="submit">保存更改</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/goodbyemszhao.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}
{% block content %}
{% bootstrap_css %}

<style>
    body{ font-family:"微软雅黑"}
    .box{ font-family:"微软雅黑"}
    p {

font-size: 20px;

}
b {

font-size: 20px;

}
</style>
<body>
    <h1 id="hh"></h1>
</body>
<script type="text/javascript">
    function station(x,y,z){
        //当前时间
        var now = Date.now(),
            //结束时间
            end = new Date(x,y-1,z),
            ends = end.getTime();
        var ss = ends - now;
        var s = Math.floor(ss/1000);
        //相差天数
        var day = Math.floor(s / 60 / 60 / 24);
        //相差小时数
        var hours = Math.floor(s / 60 / 60 % 24);
        //相差分钟数
        var min = Math.floor(s / 60 % 60 );
        //相差秒数
        var sec = Math.floor(s % 60 );
        var html = "距赵老师离开已有"+(-day-1)+"天"+(-hours-1)+"时"+(-min-1)+"分"+(-sec-1)+"秒";
        hh.innerHTML = html;
    }
    station(2023,02,25);
    //一秒一次调用
    setInterval(function(){
        station(2023,02,25);
    },1000);
</script>
<style type="text/css">
    #hh{
        font-size: 50px;
        text-align: center;
    }
</style>
<p class="box">
    亲爱的赵老师：</p>
<p style="text-indent:2em;">
            时光荏苒，岁月如梭。弹指之间，时间已过去一年半，在这段时间中，我们见证了责任、有爱、和蔼、体贴，您无微不至的关怀和体贴周到的服务，让我们这些初次远离家门的孩子重新感受到了家的温暖。一次次帮助,一次次呵护,让我们对您心生无数一次次的感动。赵老师，您和蔼可亲，您细心周到，您办事公道，您是令我们尊敬的老师，更是我们随时可以寻求帮助的朋友。</p>
<p style="text-indent:2em;">    
        如果有人问我，世界上最美的语言是什么，我想我会不假思索的回答是“谢谢”;如果有人问我，世界上最美的人是谁，我想我会毫不犹豫的回答，是您——赵老师！您是辛勤的园丁，精心呵护着祖国的花朵，让离开了家长怀抱的我们同样拥有父母般的关怀；您是不知疲倦的马达，尽力维持着学校宿管的运转，以校为家，用微薄的工资对学校做出了难以言表的贡献。</p>
<p style="text-indent:2em;"> 
    我们忘不了，看到干净整洁的宿舍时，内心的畅然；忘不了，思家孤寂时，您温存的话语慈爱的笑脸；忘不了，午夜梦回,看到寝室温馨布局时的温暖……再华丽的词藻也无法形容我们内心的感激，再美丽的语言在此刻也显得苍白无力，千言万语汇成一句话来表达我们的心声，那就是谢谢您！在今后的日子里，我们会更加努力，争取取得优异的成绩，来回报您的心血与汗水。
<p style="text-indent:2em;"> 
    最后再次感谢您，并衷心的祝愿您：身体健康，工作顺利，合家欢乐，万事如意！</p>
<p style="text-indent:2em;">    此致</p>
<p class="box">
    敬礼
</p>
<p style="text-align: right;">初2021级7班男生寝室的所有人</p>
<p style="text-align: right;">2023年2月25日</p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<b>请记住他们：</p>
<p style="text-indent:2em;">陈劲宇、范泓嘉、高梓程、何东旭、黄睿鹏、李厚辰、梁锐杰、林秘丞、林文博、刘楚晗、刘芷汛、刘卓奇、彭新鸿、蒲实、谭粟文、王浩然、王伟杰、王梓恒、肖彦博、弋凯尧、张晗、朱宏金、张秉苒</p>
    
</b>
<p></p>
<p></p>
<p></p>

{% endblock content %}

learning_logs/templates/learning_logs/important.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}
{% block content %}
{% bootstrap_css %}
<style>
    body{ font-family:"微软雅黑"}
    .box{ font-family:"微软雅黑"}
    cu{
    font-size: 20px;
}
</style>
<body>
    <ul class="navbar-nav ml-auto">
        <li>
            <cu style="color: black;">重大事件：</cu>
        </li>
        <li class="nav-item">
            <a class="nav-link" style="color: grey;" href="{% url 'learning_logs:goodbye-mszhao' %}">赵老师离开实外西区</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" style="color: grey;" href="{% url 'learning_logs:we-are-married' %}">"我们"结婚了</a>
        </li>
    
    </ul>
    <hr/>
    <ul class="navbar-nav ml-auto">
        <li>
            <cu style="color: black;">软件：</cu>
        </li>
        <li class="nav-item">
            <a class="nav-link" style="color: grey;" href="{% url 'learning_logs:new_topic'%}">新建主题</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" style="color: grey;" href="{% url 'learning_logs:topics'%}">浏览主题</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" style="color: grey;" href="{% url 'learning_logs:brief-introduction'%}">网站简介</a>
          </li>
        
    
    </ul>
    <hr/> 
        <ul class="navbar-nav ml-auto">
            <li>
                <cu style="color: black;">管理员软件：</cu>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="color: grey;" href="{% url 'users:register' %}">注册用户</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" style="color: grey;" href="{% url 'learning_logs:remove' %}">删除用户</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="color: grey;" href="https://www.pythonanywhere.com/">管理网站</a>
            </li>
            
        
        </ul>
    <hr/>

      </div>
  
  

  
  </body>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
<script>
  var noPrint=true;
  var noCopy=false;
  var noScreenshot=true;
  var autoBlur=false;
</script>
<script type="text/javascript" src="https://pdfanticopy.com/noprint.js"></script>
  <div class="jumbotron">
    <h1 class="display-3">欢迎来到Baboon协会</h1>

    <p class="lead">Welcome to the Baboon baboonassociation</p>
    
    <a class="btn btn-primary input-sm" href="{% url 'learning_logs:home'%}" role="button">网站功能 &raquo;</a>
    </div>
    <!--
    <h3><strong><p style="color:red">喜报！</p></strong></h3>
    <div class="test1">

      <ul>
      
      <img id="pic" src="https://imglf6.lf127.net/img/1d635c1c04e3e338/RE90NFpEV1NHVzNwQnRlNVhMUXpSS2dzMWRjWGVNSTN1RnBUR2huOVpJMD0.jpg?imageView&thumbnail=500x0&quality=96&stripmeta=0&type=jpg" width=800>

      </ul>
      
      </div>
      
      </body>
      
      <script>
      
        var pic=document.getElementById("pic");
        var a="https://imglf6.lf127.net/img/1d635c1c04e3e338/RE90NFpEV1NHVzNwQnRlNVhMUXpSS2dzMWRjWGVNSTN1RnBUR2huOVpJMD0.jpg?imageView&thumbnail=500x0&quality=96&stripmeta=0&type=jpg"
        var b="https://imglf4.lf127.net/img/c4045c1e2427119e/RE90NFpEV1NHVzNwQnRlNVhMUXpST2kwL2dQSFdRUXVwVVZTK3RXWGZRRT0.png?imageView&thumbnail=1680x0&quality=96&stripmeta=0"
        var c="https://imglf3.lf127.net/img/11f16e6475ad838a/RE90NFpEV1NHVzNwQnRlNVhMUXpSS1c2K1NYZWJ4L0szc2Y5N2FEVXgrND0.png?imageView&thumbnail=1680x0&quality=96&stripmeta=0"
        var arr=new Array(a,b,c);
      
        var imgIndex=0;
      
        function pic_Change(){                   /*构造换图函数*/
      
            if(imgIndex==2){
               imgIndex=0;

               }
            else{
               imgIndex++;}
            pic.src=arr[imgIndex];          /*这里把arr[imgIndex]赋给pic中的src来改变原src的值（即原图片）*/
              
            }
      
        var picc=setInterval(pic_Change,3000); /*执行语句*/
      
      </script>-->
    <!--<img src="https://thumbnail0.baidupcs.com/thumbnail/a68e7c255s6732f53069300a3b7b02db?fid=837566511-250528-484134578117237&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-%2bDldsDAG3kYNQ41YDAvZxCjd1eM%3d&expires=8h&chkbd=0&chkv=0&dp-logid=175939124802204092&dp-callid=0&time=1671685200&size=c1999_u1999&quality=100&vuk=837566511&ft=image" width=800>
    <a href="https://pan.baidu.com/s/11QszBbMI3NIvlo1jJzifIA?pwd=1234" id="box">下载结婚照</a>-->
    {% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
    
  <p>添加条目:</p>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary input-sm" name='submit'>添加条目</button>
  </form>
    
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <p>新建主题：</p>
    
  <form action="{% url 'learning_logs:new_topic' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary input-sm" name="submit">提交</button>
  </form>
    
{% endblock content %}

learning_logs/templates/learning_logs/remove-list.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
<h1 style="color: red;">
    删除用户
</h1>


<form action="" method="post">
    {% csrf_token %}
    {{ forms }}
    <input type="Submit" value="删除此用户" class="btn btn-primary input-sm"/>
</form>
{% if messages %}
            {% for msg in messages %}
            <script>
                alert('{{ msg.message }}');
            </script>
            {% endfor %}
{% endif %}
{% endblock page_header %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
  <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
  <p>
    <a class="btn btn-primary input-sm" href="{% url 'learning_logs:new_entry' topic.id %}">添加新条目</a>
  </p>

  <ul>
  {% for entry in entries %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
          编辑条目</a></small>
      </h4>
      <div class="card-body">
        {{ entry.text|linebreaks }}
      </div>
    </div>
  {% empty %}
    <p>没有条目</p>
  {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h1>主题</h1>
{% endblock page_header %}

{% block content %}
  <ul>
    {% for topic in topics %}
      <li><h3>
        <a style="color: gray;" href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
      </h3></li>
    {% empty %}
      <li><h3>没有条目</h3></li>
    {% endfor %}
  </ul>

  <h3><a class="btn btn-primary input-sm" href="{% url 'learning_logs:new_topic' %}">添加新主题</a></h3>

{% endblock content %}

learning_logs/templates/learning_logs/we-are-married.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}
{% block content %}
{% bootstrap_css %}
<h3><strong><p style="color:red">喜报！</p></strong></h3>
<h5><p style="color:red">我们结婚了！</p></h5>
<img src="https://imglf6.lf127.net/img/1d635c1c04e3e338/RE90NFpEV1NHVzNwQnRlNVhMUXpSS2dzMWRjWGVNSTN1RnBUR2huOVpJMD0.jpg?imageView&thumbnail=500x0&quality=96&stripmeta=0&type=jpg">
<p></p>
<a href="https://pan.baidu.com/s/11QszBbMI3NIvlo1jJzifIA?pwd=1234" id="box">下载结婚照</a>
<p></p>
<a href="/" style="color: gray;">点我返回</a>
{% endblock content %}